version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=development
